repos:
  - repo: https://github.com/pycqa/flake8.git
    rev: 7.1.1
    hooks:
      - id: flake8
        exclude: |
            (?x)^(
                examples/|
                docs/|
                tests/|
                evalscope/utils/utils.py|
                evalscope/third_party/|
                evalscope/backend/rag_eval/clip_benchmark/tasks|
                evalscope/backend/rag_eval/cmteb/tasks|
                evalscope/metrics/t2v_metrics
            )
  - repo: https://github.com/PyCQA/isort.git
    rev: 6.0.1
    hooks:
      - id: isort
  - repo: https://github.com/google/yapf
    rev: v0.43.0
    hooks:
      - id: yapf
        exclude: |
            (?x)^(
                examples/|
                docs/|
                tests/|
                evalscope/utils/utils.py|
                evalscope/third_party/|
                evalscope/backend/rag_eval/clip_benchmark/tasks|
                evalscope/backend/rag_eval/cmteb/tasks
            )
  - repo: https://github.com/pre-commit/pre-commit-hooks.git
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        exclude: thirdparty/|docs/|examples
      - id: check-yaml
        exclude: thirdparty/|docs/|examples
      - id: end-of-file-fixer
        exclude: thirdparty/|docs/|examples
      - id: requirements-txt-fixer
        exclude: thirdparty/|docs/|examples
      - id: double-quote-string-fixer
        exclude: thirdparty/|docs/|examples
      - id: check-merge-conflict
        exclude: thirdparty/|docs/|examples
      - id: mixed-line-ending
        exclude: thirdparty/|docs/|examples
        args: ["--fix=lf"]
